version: "3"

services:
  prom:
    image: prom/prometheus:v2.21.0
    container_name: prom-docker
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command: --web.enable-lifecycle --config.file=/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  postgres:
    image: postgres
    container_name: pg-docker
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=spring
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  prometheus_data: