# Spring Boot config
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/spring
    username: postgres
    password: password

resilience4j.ratelimiter:
  instances:
    getPeople:
      # how many requests are allowed within one period?
      limitForPeriod: 2
      # how long before the period resets?
      limitRefreshPeriod: 15s
      # how long does the thread wait for permission?
      timeoutDuration: 1000ms
resilience4j.bulkhead:
  instances:
    # these values are just for testing
    # should be changed for an actual production setup
    getPeople:
      maxWaitDuration: 100ms
      maxConcurrentCalls: 1

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"